### ISSUE TITLE
Deprecated gem

### ISSUE THREAD

**Issue by gildub** [ManageIQ/manageiq-network_discovery#11]
Since https://github.com/ManageIQ/manageiq/pull/16946 this gem is not used any more.

**Comment by Fryguy** [comment]
@gildub Can you change the master branch's README to reflect that this gem is no longer maintained?

**Comment by gildub** [comment]
@Fryguy, added https://github.com/ManageIQ/manageiq-network_discovery/pull/12 , thanks.

**Comment by Fryguy** [comment]
Closed in #12
