### ISSUE TITLE
All probes to be moved to respective provider

### ISSUE THREAD

**Issue by gildub** [ManageIQ/manageiq-network_discovery#8]
All network discovery probes to be relocated to their respective ems providers or to helper files in the case of IPMI (ultimately this one would end up in a generic provider).

Following same approach as https://github.com/ManageIQ/manageiq-providers-openstack/pull/115.
The later was driven by https://bugzilla.redhat.com/show_bug.cgi?id=1212947 to add discovery for OpenStack.

Probes module are regrouped by providers.

The new name space `ManageIQ::Network::Discovery` allows transition from   `ManageIQ::NetworkDiscovery`

The new approach is defined in
- [x] https://github.com/ManageIQ/manageiq/pull/16916
but won't be used until the switch over is activated with   
- [x] https://github.com/ManageIQ/manageiq/pull/16946

The following PRs are the probes relocation, which won't be used until PR#16946 is merged:
- [x] OpenStack: https://github.com/ManageIQ/manageiq-providers-openstack/pull/215
- [x] OpenStack re-factor: https://github.com/ManageIQ/manageiq-providers-openstack/pull/220
- [x] rhevm - https://github.com/ManageIQ/manageiq-providers-ovirt/pull/118
- [x] VMware: https://github.com/ManageIQ/manageiq-providers-vmware/pull/181
- [x] Windows probes: https://github.com/ManageIQ/manageiq-providers-scvmm/pull/61
- [x] IPMI is included in core (for now)

Since name space issue due to RoR Model STI using `Network` for ems_infra, in https://github.com/ManageIQ/manageiq/pull/16994 has replaced `ManageIQ::Network` with `ManageIQ::NetworkDiscovery`, the core activation (https://github.com/ManageIQ/manageiq/pull/16946) was updated and all the probes using the library have to be updated too:  
- [x] openstack -https://github.com/ManageIQ/manageiq-providers-openstack/pull/227
- [x] rhevm - https://github.com/ManageIQ/manageiq-providers-ovirt/pull/208 
- [x] rhevm - require line - https://github.com/ManageIQ/manageiq-providers-ovirt/pull/209 
- [x] vmware - https://github.com/ManageIQ/manageiq-providers-vmware/pull/183
- [x] windows - https://github.com/ManageIQ/manageiq-providers-scvmm/pull/63

Also used opportunity to move IPMI probe to proper name space using `Util::IPMI`:
- [x] IPMI move to `Util` - https://github.com/ManageIQ/manageiq/pull/16999

**Comment by gildub** [comment]
@Fryguy, @chessbyte, would it be ok to add me to the assignee list?

**Comment by gildub** [comment]
@Fryguy, @chessbyte, I wonder where the IPMI probe should be moved to as IPMI are more tools and helpers unless there is a plan for a provider or dedicated gem for it. What do you think?

**Comment by borod108** [comment]
@gildub can you please elaborate a bit on what is this, why do we need it and how it is used?
We try to support both v3 and v4 of the rhv api, this code seems to only use v3 which one day might be a problem. (We support both apis for refresh, event handling, provisioning etc.)

**Comment by gildub** [comment]
@borod108,

While adding probe for OpenStack I realized each provider should be maintaining its own probe(s), there is no need for a dedicated repo/gem, so once we' ve moved the probes, the base can go back to manageiq/manageiq and we won't need this repo anymore.  

As per your comment about RHV API  version support, I have no idea of the details, meanwhile it seems to reinforce this idea to move closer to the provider.

**Comment by gildub** [comment]
To facilitate the move for all related providers, I propose to duplicate the "core" network discovery code into manageiq/manageiq first and then move the probes to their providers. 
To avoid any overlap the move use `network/discovery` instead of `network_discovery`.
